image: python:latest

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - export PYTHONPATH=$(pwd)/..:$PYTHONPATH
  - apt-get -qq update && apt-get -qq install -y texlive texlive-latex-extra texlive-science

cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - build
  - prod

installation:
  stage: build
  script:
    - python -m pip install matplotlib numpy scipy --upgrade

prod_mpl:
  stage: prod
  script:
    - cd examples/
    - for file in $(find $(pwd) -type f -iname matplotlib_example.py) ; do echo $file ; cd $(dirname $file) ; python matplotlib_example.py ; done

prod_ltLaTeXpyplot:
  stage: prod
  script:
    - cd examples/
    - for file in $(find $(pwd) -type f -iname ltLaTeXpyplot_example.py) ; do echo $file ; cd $(dirname $file) ; ./ltLaTeXpyplot_example.py ; done
  artifacts:
    paths:
    - examples/