image: python:latest

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - export PYTHONPATH=$(pwd)/..:$PYTHONPATH
  - export instal_dir=$(pwd)
  - export APT_CACHE_DIR=`pwd`/apt-cache && mkdir -pv $APT_CACHE_DIR
  - export PATH=$APT_CACHE_DIR:$PATH

cache:
  paths:
    - .cache/pip
    - venv/
    - apt-cache/

stages:
  - build
  - prod

installation:
  stage: build
  script:
    - apt-get -qq update && apt-get -qq -o dir::cache::archives="$APT_CACHE_DIR" install -y texlive texlive-latex-extra texlive-science
    - python3 -m pip install matplotlib numpy scipy --upgrade

prod_Fct3d:
  stage: prod
  script:
    - cd examples/Fct3d && ./ltLaTeXpyplot_example.py
  artifacts:
    paths:
    - examples/Fct3d

prod_simple_plot:
  stage: prod
  script:
    - cd examples/simple_plot && ./ltLaTeXpyplot_example.py
  artifacts:
    paths:
    - examples/simple_plot