image: python:latest

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - build
  - prod

installation:
  stage: build
  script:
    - apt-get -qq update && apt-get -qq install -y python3-numpy python3-scipy python3-matplotlib texlive texlive-latex-extra texlive-science
    - python3 -m pip install matplotlib --upgrade
    - export PYTHONPATH=$(pwd)/..:$PYTHONPATH
    - export instal_dir=$(pwd)
  cache:
    paths:
      - .cache/pip
      - venv/

prod_Fct3d:
  stage: prod
  script:
    - cd examples/Fct3d && ./ltLaTeXpyplot_example.py
  artifacts:
    paths:
    - examples/Fct3d

prod_simple_plot:
  stage: prod
  script:
    - cd examples/simple_plot && ./ltLaTeXpyplot_example.py
  artifacts:
    paths:
    - examples/simple_plot