#!/bin/bash

name="ltLaTeXpyplot python package"

echo "Installing $name..."

ainstal_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
ainstal_dir=${ainstal_dir%"ltLaTeXpyplot"}

if [[ $(grep -l "$name" ~/.bashrc) = ~/.bashrc ]]
then
    echo 'It seems like you already have installed this!'
    echo 'Not changing anything.'
else
    if [[ $ainstal_dir = $HOME* ]]
    then
        instal_dir=~${ainstal_dir#$HOME}
    else
        instal_dir=$ainstal_dir
    fi
    echo "" >> ~/.bashrc
    echo "# --- add $name ---" >> ~/.bashrc
    if [[ $PYTHONPATH != *$ainstal_dir* ]]
    then
        echo "export PYTHONPATH=$instal_dir:"'$PYTHONPATH' >> ~/.bashrc
    fi
    echo "Installation completed."
fi
